# Deployment for server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server   # this is the label for the pod
  template:               # this configures the pod
    metadata:
      labels:
        component: server # this is the label for the pod
    spec:
      containers:
        - name: server # this is the name of the container
          image: rallycoding/multi-server # this is the image we want to use
          ports:
            - containerPort: 5000 # this is the port we want to expose
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGPORT
              value: 5432'
            - name: PGDATABASE
              value: postgres

            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword 
                  key: PGPASSWORD

          resources:
            limits:
              memory: "256Mi" # 256 MB
              cpu: "500m" # 500 millicpu (.5 cpu)

---
# Service for server
apiVersion: v1
kind: Service # this is the service
metadata: # this is the metadata
  name: server-cluster-ip-service # this is the name of the service
spec: 
  type: ClusterIP # this is the default type
  selector:                   # which pod we are talking to
    component: server         # this is the label for the pod
  ports:
    - port: 5000              # ingress
      targetPort: 5000  